In [ ]:
#variables and data types
five = 5 #integer
pi = 3.14 # float
name = "ram" # string
my_num = "2" #string
my_list = [1,2,3,4,5] #list
my_tuple = (1,2,3) #tuple
my_dict = {'name':'ram','age': 18} #dictionary


In [ ]:
my_list[1] = 5

In [ ]:
my_list

[1, 5, 3, 4, 5]

In [ ]:
c = "2"
b = "3"

In [ ]:
#concatenation
a = b + c
print(a)

32


In [ ]:
#ifelse
num_range = int(input("Enter a number"))
if num_range > 18:
  print("Number is greater than 18")
elif num_range == 18:
  print("Number is equal to 18")
else:
  printz("Number is less than 18")

Enter a numberafrina


ValueError: invalid literal for int() with base 10: 'afrina'

In [ ]:
num_range = str(input("Enter a number:"))

Enter a number:afrina


In [ ]:
for number in range(1,11):
  print(number)


1
2
3
4
5
6
7
8
9
10


In [ ]:
age = int(input("Enter your age:"))
while age < 18:
  print("You are only" ,age,"Not eligible to vote")
  age +=3

Enter your age:3
You are only 3 Not eligible to vote
You are only 6 Not eligible to vote
You are only 9 Not eligible to vote
You are only 12 Not eligible to vote
You are only 15 Not eligible to vote


In [ ]:
#function
def greet(name):
  print("Hey" , name ,"How are you?")

def food(name):
  print("Hi",name,"Have you completed your lunch?")

greet("rina")
food("parina")

Hey rina How are you?
Hi parina Have you completed your lunch?


In [ ]:
def addition(x,y):
  z = x + y
  print(z)
def subtraction(x,y):
  print(x-y)


In [ ]:
addition(2,3)

5


In [ ]:
subtraction(2,3)

-1


In [ ]:
import numpy as np


In [ ]:
import pandas as pd


In [ ]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr1[0]

1

In [ ]:
arr2[1][0]

3

In [ ]:
arr3[1]

array([[5, 6],
       [7, 8]])

In [ ]:
arr3[1][0]


array([5, 6])

In [ ]:
arr3[1][0][0]


5

In [ ]:
df1= pd.DataFrame({'name':['parithie','afrina','john','anisha','aira']})
print(df1)

       name
0  parithie
1    afrina
2      john
3    anisha
4      aira


In [ ]:
df1.tail()

name
0  parithie
1    afrina
2      john
3    anisha
4      aira

In [ ]:
df1.head(3)

name
0  parithie
1    afrina
2      john

In [ ]:
df1.shape

(5, 1)

In [ ]:
df2 = pd.read_csv("/content/income.csv")

In [ ]:
df2.head()

Name  Age  Income($)
0      Rob   27      70000
1  Michael   29      90000
2    Mohan   29      61000
3   Ismail   28      60000
4     Kory   42     150000

In [ ]:
df2.shape

(22, 3)

In [ ]:
df2.describe

<bound method NDFrame.describe of         Name  Age  Income($)
0        Rob   27      70000
1    Michael   29      90000
2      Mohan   29      61000
3     Ismail   28      60000
4       Kory   42     150000
5     Gautam   39     155000
6      David   41     160000
7     Andrea   38     162000
8       Brad   36     156000
9   Angelina   35     130000
10    Donald   37     137000
11       Tom   26      45000
12    Arnold   27      48000
13     Jared   28      51000
14     Stark   29      49500
15    Ranbir   32      53000
16    Dipika   40      65000
17  Priyanka   41      63000
18      Nick   43      64000
19      Alia   39      80000
20       Sid   41      82000
21     Abdul   39      58000>